In [140]:
## for data
import pandas as pd
import numpy as np
from numpy import cov

## for plotting
import matplotlib.pyplot as plt
import seaborn as sns

## for statistical tests
import scipy
import statsmodels.formula.api as smf
import statsmodels.api as sm
import statistics
from scipy.stats import pearsonr
import math

## for machine learning
import sklearn
from sklearn import preprocessing, svm
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

import string

Here is my data imported via pandas:

In [141]:
df = pd.read_csv('fdata.csv', encoding = "ISO-8859-1")


#This is the complete list of games from the 2020 NFL season. I am going to clean up the data here in this notebook before 
#reassembling it into a df.

In [142]:
def PointTotals(lst):
    point_totals = []
    for i in lst:
        total_score = int(i[0:2]) + int(i[3:5])
        point_totals.append(total_score)
    return point_totals
    
point_total = PointTotals(df['score'])

#This function adds the point totals together for all of the games, giving us the total score. One flaw with this is that I had
#to go through the excel file and make sure every score had two values i.e. "09" instead of "9"

In [143]:

def CleanUp_TeamNames(lst):
    letters = string.ascii_lowercase
    new_list = []
    
    for word in lst:
        new_word = ''
        for character in word:
            if character.lower() in letters:
                new_word += character
            else:
                break 
        new_list.append(new_word)
   
    return new_list
                        
        
Team1New = CleanUp_TeamNames(df['team 1'])
Team2New = CleanUp_TeamNames(df['team 2'])
             
#This function cleans up the team names so that the data from the website gets trimmed down to just the actual team name

In [144]:
week_list = df['week number']

In [145]:
#in the block below I am going to try and make a function that takes a file name as an input and returns a df with the averages
#for the stats I want by week

In [183]:
def AveragedDataFrame(file_name):
    
    working_df = pd.read_csv(file_name, encoding = "ISO-8859-1")
    
    new_df = pd.DataFrame(index = working_df.loc[1:, 'Week'] )
    
    #this is the function to get the averages for the columns
    def GetTheAverages(column_name):
        averaged_list = []
        total = 0
        count = 0
        for item in column_name[1:]:
            total += column_name[count]
            count += 1
            average = total/count
            averaged_list.append(average)
        return averaged_list
  
    
    TmList = GetTheAverages(working_df['Tm'])
    OpList = GetTheAverages(working_df['Opp'])
    D1List = GetTheAverages(working_df['D1'])
    TYList = GetTheAverages(working_df['TY'])
    PYList = GetTheAverages(working_df['PY'])
    RYList = GetTheAverages(working_df['RY'])
    D1AList = GetTheAverages(working_df['D1A'])
    TYAList = GetTheAverages(working_df['TYA'])
    PYAList = GetTheAverages(working_df['PYA'])
    RYAList = GetTheAverages(working_df['RYA'])
    OXPList = GetTheAverages(working_df['OXP'])
    DXPList = GetTheAverages(working_df['DXP'])
    STXPList = GetTheAverages(working_df['STXP'])
    
    
    
    #new_df['Week'] = working_df.loc[1:, 'Week']
    new_df['AveragedTm'] = TmList
    new_df['AveragedOp'] = OpList      
    new_df['AveragedD1'] = D1List       
    new_df['AveragedTY'] = TYList       
    new_df['AveragedPY'] = PYList   
    new_df['AveragedRY'] = RYList
    new_df['AveragedD1A'] = D1AList
    new_df['AveragedTYA'] = TYAList
    new_df['AveragedPYA'] = PYAList
    new_df['AveragedRYA'] = RYAList
    new_df['AveragedOXP'] = OXPList        
    new_df['AveragedDXP'] = DXPList        
    new_df['AveragedSTXP'] = STXPList   
    



    return new_df

In [206]:
Bills = AveragedDataFrame('bills2020.csv')
Broncos = AveragedDataFrame('broncos2020.csv')
Chargers = AveragedDataFrame('chargers2020.csv')
Raiders = AveragedDataFrame('raiders2020.csv')
Chiefs = AveragedDataFrame('chiefs2020.csv')
Jaguars = AveragedDataFrame('jaguars2020.csv')
Texans = AveragedDataFrame('texans2020.csv')
Colts = AveragedDataFrame('colts2020.csv')
Titans = AveragedDataFrame('titans2020.csv')
Bengals = AveragedDataFrame('bengals2020.csv')
Ravens = AveragedDataFrame('ravens2020.csv')
Browns = AveragedDataFrame('browns2020.csv')
Steelers = AveragedDataFrame('steelers2020.csv')
Jets = AveragedDataFrame('jets2020.csv')
Patriots = AveragedDataFrame('patriots2020.csv')
Dolphins = AveragedDataFrame('dolphins2020.csv')


list_of_dataframes = [Bills, Broncos, Chargers, Raiders, Chiefs, Jaguars, Texans, Colts, Titans, Bengals, Ravens, Browns, Steelers, Patriots, Dolphins]

In [249]:
def BuildOut(column_name, team_list):
    lst = []
    
    name = column_name[:-2]
    week_row_counter = 0
    
    
    for week_number in week_list:
       
        for i in team_list[week_row_counter:]: 
            
            for df in list_of_dataframes:
                
                if i != str(df):
                    
                    continue
                
                else:
                    
                    print(week_number)
                    
                    number2 = df.index.get_loc(week_number)
                    
                    value = df.loc(number2 , name)
                    
                    lst.append(value)
                    
                    week_row_counter += 1
                    
                    
                    
               
                break
                
            break
                
            
           
    return lst

In [250]:
master_df = pd.DataFrame()

#master_df['Total Scores'] = point_total
#master_df['Team 1'] = Team1New
#master_df['Team 2'] = Team2New
#master_df['Week'] = week_list
master_df['AveragedTm T1'] = BuildOut('AveragedTm', Team1New)
#master_df['AveragedOp T1'] = [0 for i in range(0,240)]    
#master_df['AveragedD1 T1'] =  [0 for i in range(0,240)]     
#master_df['AveragedTY T1'] =  [0 for i in range(0,240)]  
#master_df['AveragedPY T1'] =  [0 for i in range(0,240)]
#master_df['AveragedRY T1'] = [0 for i in range(0,240)]
#master_df['AveragedD1A T1'] = [0 for i in range(0,240)]
#master_df['AveragedTYA T1'] = [0 for i in range(0,240)]
#master_df['AveragedPYA T1'] = [0 for i in range(0,240)]
#master_df['AveragedRYA T1'] = [0 for i in range(0,240)]
#master_df['AveragedOXP T1'] = [0 for i in range(0,240)]   
#master_df['AveragedDXP T1'] = [0 for i in range(0,240)]       
#master_df['AveragedSTXP T1'] = [0 for i in range(0,240)]  
#master_df['AveragedTm T2'] = [0 for i in range(0,240)]
#master_df['AveragedOp T2'] = [0 for i in range(0,240)]    
#master_df['AveragedD1 T2'] = [0 for i in range(0,240)]      
#master_df['AveragedTY T2'] =[0 for i in range(0,240)] 
#master_df['AveragedPY T2'] = [0 for i in range(0,240)]
#master_df['AveragedRY T2'] = [0 for i in range(0,240)]
#master_df['AveragedD1A T2'] = [0 for i in range(0,240)]
#master_df['AveragedTYA T2'] = [0 for i in range(0,240)]
#master_df['AveragedPYA T2'] = [0 for i in range(0,240)]
#master_df['AveragedRYA T2'] = [0 for i in range(0,240)]
#master_df['AveragedOXP T2'] = [0 for i in range(0,240)]      
#master_df['AveragedDXP T2'] = [0 for i in range(0,240)]     
#master_df['AveragedSTXP T2'] = [0 for i in range(0,240)]

In [251]:
print(master_df)

Empty DataFrame
Columns: [AveragedTm T1]
Index: []

In [252]:
print(dolphins)

value = dolphins.index.get_loc(3) 
print(value)

      AveragedTm  AveragedOp  AveragedD1  AveragedTY  AveragedPY  AveragedRY  \
Week
2      11.000000   21.000000   20.000000  269.000000  182.000000   87.000000
3      19.500000   26.000000   24.000000  339.500000  246.500000   93.000000
4      23.333333   21.666667   23.666667  324.333333  216.333333  108.000000
5      23.250000   24.000000   24.000000  347.000000  240.250000  106.750000
6      27.200000   22.600000   23.600000  364.800000  260.600000  104.200000
8      26.666667   18.833333   22.666667  354.333333  249.166667  105.166667
9      26.857143   18.571429   20.571429  324.428571  226.428571   98.000000
10     27.750000   20.125000   21.000000  322.875000  225.750000   97.125000
11     27.888889   20.222222   20.555556  318.111111  219.444444   98.666667
12     26.400000   20.200000   20.200000  308.600000  214.200000   94.400000
13     25.818182   18.636364   20.363636  311.909091  216.636364   95.272727
14     25.250000   17.666667   20.583333  319.750000  223.250000   96.500000
15     25.384615   18.846154   21.076923  323.384615  228.153846   95.230769
16     25.142857   18.357143   21.428571  327.642857  221.357143  106.285714
17     25.200000   18.800000   21.200000  331.333333  223.466667  107.866667

      AveragedD1A  AveragedTYA  AveragedPYA  AveragedRYA  AveragedOXP  \
Week
2       29.000000   357.000000   140.000000   217.000000    -2.200000
3       26.000000   440.000000   275.500000   164.500000     5.250000
4       24.666667   399.333333   265.666667   133.666667     7.810000
5       25.000000   409.750000   285.000000   124.750000     7.637500
6       23.800000   379.600000   253.600000   126.000000     9.982000
8       22.000000   360.166667   236.000000   124.166667     8.371667
9       23.285714   376.000000   250.857143   125.142857     4.085714
10      23.625000   384.250000   252.500000   131.750000     5.485000
11      23.111111   371.888889   243.777778   128.111111     3.991111
12      22.700000   380.600000   246.400000   134.200000     2.916000
13      21.545455   369.636364   239.727273   129.909091     2.823636
14      20.750000   355.166667   232.750000   122.416667     3.083333
15      20.846154   362.307692   242.076923   120.230769     3.646154
16      20.642857   358.071429   238.071429   120.000000     4.579286
17      20.800000   362.066667   243.133333   118.933333     4.675333

      AveragedDXP  AveragedSTXP
Week
2      -14.110000      5.640000
3      -17.635000      3.970000
4       -9.886667      2.023333
5      -11.442500      1.847500
6       -7.258000      1.484000
8       -3.020000      1.868333
9        0.041429      3.374286
10      -2.206250      3.747500
11      -1.752222      4.961111
12      -2.497000      4.957000
13      -0.904545      4.780000
14      -0.229167      4.242500
15      -0.489231      2.828462
16      -0.382857      2.186429
17      -1.105333      2.254667
1